/* "Where I've been" interactive map. Leaflet is vendored (js/leaflet.js, css/leaflet.css).
   Data comes from <script type="application/json" id="places-data"> (generated by build.py). */
(function () {
  var wrap = document.getElementById("places-map-wrap");
  var dataEl = document.getElementById("places-data");
  var mapEl = document.getElementById("places-map");
  if (!wrap || !dataEl || !mapEl || typeof L === "undefined") return; // <noscript> list stays visible

  var places;
  try { places = JSON.parse(dataEl.textContent); } catch (e) { return; }
  var noscript = wrap.parentNode.querySelector("noscript");
  wrap.hidden = false;
  if (noscript) noscript.setAttribute("aria-hidden", "true");

  var filterEl = document.getElementById("pm-filter");
  var listEl = document.getElementById("pm-list");
  var statusEl = document.getElementById("pm-status");
  var hintEl = document.getElementById("pm-hint");
  var touch = !!(window.matchMedia && window.matchMedia("(pointer: coarse)").matches);
  var reduce = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  var map = L.map(mapEl, {
    scrollWheelZoom: false,       // enabled only after the map is clicked / focused
    dragging: !touch,             // one-finger drag would hijack page scroll on phones
    tap: false,
    minZoom: 0, maxZoom: 14,
    zoomSnap: 0.25,
    worldCopyJump: false,
    maxBounds: [[-75, -200], [85, 200]],
    maxBoundsViscosity: 0.8,
    attributionControl: true
  });
  // TILES: CARTO's raster basemaps now watermark every keyless tile ("API KEY REQUIRED", since Sept 2026),
  // so the default is Esri's keyless World Dark Gray canvas (+ labels layer). To switch to CARTO dark_all,
  // get a free key at https://carto.com/basemaps/apikey/ and set CARTO_KEY below.
  var CARTO_KEY = "";
  if (CARTO_KEY) {
    L.tileLayer("https://{s}.basemaps.cartocdn.com/rastertiles/dark_all/{z}/{x}/{y}{r}.png?key=" + CARTO_KEY, {
      subdomains: "abcd", maxZoom: 14,
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>'
    }).addTo(map);
  } else {
    var esri = "https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/";
    L.tileLayer(esri + "World_Dark_Gray_Base/MapServer/tile/{z}/{y}/{x}", {
      maxZoom: 14, maxNativeZoom: 16,
      attribution: 'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ &middot; Data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);
    L.tileLayer(esri + "World_Dark_Gray_Reference/MapServer/tile/{z}/{y}/{x}", { maxZoom: 14, maxNativeZoom: 16, pane: "shadowPane" }).addTo(map);
  }

  function yearText(p) {
    return p.years.map(function (y) { return y.y + (y.tag ? " (" + y.tag + ")" : ""); }).join(" \u00b7 ");
  }
  function firstYear(p) { return Math.min.apply(null, p.years.map(function (y) { return y.y; })); }
  places.sort(function (a, b) { return firstYear(a) - firstYear(b) || a.name.localeCompare(b.name); });

  function popupFor(p) {
    var d = document.createElement("div");
    d.className = "pm-popup";
    var h = document.createElement("strong"); h.textContent = p.name; d.appendChild(h);
    var sub = [p.sub, p.note, p.approx ? "Pin at " + p.approx + " (approximate)" : ""].filter(Boolean);
    sub.forEach(function (t) { var s = document.createElement("span"); s.className = "pm-sub"; s.textContent = t; d.appendChild(s); });
    var y = document.createElement("span"); y.className = "pm-years"; y.textContent = yearText(p); d.appendChild(y);
    return d;
  }

  var layer = L.layerGroup().addTo(map);
  var activeItem = null;
  places.forEach(function (p) {
    var icon = L.divIcon({ className: "pm-pin", html: "<span></span>", iconSize: [22, 22], iconAnchor: [11, 11], popupAnchor: [0, -11] });
    p.marker = L.marker([p.lat, p.lng], { icon: icon, title: p.name + ", " + yearText(p), alt: p.name, riseOnHover: true, keyboard: true });
    p.marker.bindPopup(popupFor(p), { closeButton: true, autoPanPadding: [24, 24], maxWidth: 260 });
    p.marker.on("popupopen", function () { setActive(p); });
    p.marker.on("popupclose", function () { setActive(null); });

    var li = document.createElement("li");
    var b = document.createElement("button");
    b.type = "button"; b.className = "pm-item";
    var n = document.createElement("span"); n.className = "pm-item-name"; n.textContent = p.name + (p.sub ? " \u2013 " + p.sub : "");
    var yy = document.createElement("span"); yy.className = "pm-item-years"; yy.textContent = yearText(p);
    b.appendChild(n); b.appendChild(yy);
    b.addEventListener("click", function () { flyTo(p); });
    li.appendChild(b);
    p.item = li; p.btn = b;
    listEl.appendChild(li);
  });

  function setActive(p) {
    if (activeItem) { activeItem.btn.classList.remove("is-active"); activeItem.btn.removeAttribute("aria-current"); activeItem.marker.getElement() && activeItem.marker.getElement().classList.remove("is-active"); }
    activeItem = p;
    if (p) { p.btn.classList.add("is-active"); p.btn.setAttribute("aria-current", "true"); p.marker.getElement() && p.marker.getElement().classList.add("is-active"); }
  }

  function flyTo(p) {
    var z = Math.max(map.getZoom(), 6);
    var target = [p.lat, p.lng];
    if (reduce) map.setView(target, z, { animate: false }); else map.flyTo(target, z, { duration: 1.1 });
    p.marker.openPopup();
    mapEl.scrollIntoView({ block: "nearest", behavior: reduce ? "auto" : "smooth" });
  }

  // Year filter
  var yearSet = {};
  places.forEach(function (p) { p.years.forEach(function (y) { yearSet[y.y] = true; }); });
  var years = Object.keys(yearSet).map(Number).sort(function (a, b) { return a - b; });
  var current = "all";
  var buttons = [];
  function mkBtn(label, val) {
    var b = document.createElement("button");
    b.type = "button"; b.className = "pm-year"; b.textContent = label; b.dataset.val = val;
    b.setAttribute("aria-pressed", val === "all" ? "true" : "false");
    b.addEventListener("click", function () { applyFilter(val); });
    filterEl.appendChild(b); buttons.push(b);
  }
  mkBtn("All", "all");
  years.forEach(function (y) { mkBtn(String(y), String(y)); });

  function fit(list) {
    if (!list.length) return;
    var b = L.latLngBounds(list.map(function (p) { return [p.lat, p.lng]; }));
    var opts = { padding: [36, 36], maxZoom: 7, animate: !reduce };
    if (list.length === 1) map.setView(b.getCenter(), 6, { animate: !reduce }); else map.fitBounds(b, opts);
  }

  function applyFilter(val) {
    current = val;
    buttons.forEach(function (b) { b.setAttribute("aria-pressed", b.dataset.val === val ? "true" : "false"); });
    map.closePopup();
    var shown = places.filter(function (p) { return val === "all" || p.years.some(function (y) { return String(y.y) === val; }); });
    places.forEach(function (p) {
      var on = shown.indexOf(p) !== -1;
      p.item.hidden = !on;
      if (on) layer.addLayer(p.marker); else layer.removeLayer(p.marker);
    });
    statusEl.textContent = val === "all"
      ? places.length + " places, 2011\u20132026."
      : shown.length + (shown.length === 1 ? " place" : " places") + " in " + val + ": " + shown.map(function (p) { return p.name; }).join(", ") + ".";
    fit(shown);
  }

  // Scroll-zoom only after the map is clicked / focused
  function enableWheel() { map.scrollWheelZoom.enable(); hintEl.textContent = "Scroll to zoom. Click outside the map to turn it off."; }
  function disableWheel() { map.scrollWheelZoom.disable(); hintEl.textContent = touch ? "Pinch to zoom. Use the list to explore." : "Click the map to enable scroll-zoom."; }
  map.on("click focus", enableWheel);
  mapEl.addEventListener("mouseleave", disableWheel);
  map.on("blur", disableWheel);
  disableWheel();

  applyFilter("all");
  // Reveal animation / layout shifts: keep tiles sized correctly.
  window.addEventListener("load", function () { map.invalidateSize(); fit(places.filter(function (p) { return !p.item.hidden; })); });
  window.addEventListener("resize", function () { map.invalidateSize(); });
})();
