/* "Where I've been" interactive map. Leaflet is vendored (js/leaflet.js, css/leaflet.css).
   Data comes from <script type="application/json" id="places-data"> (generated by build.py). */
(function () {
  var wrap = document.getElementById("places-map-wrap");
  var dataEl = document.getElementById("places-data");
  var mapEl = document.getElementById("places-map");
  if (!wrap || !dataEl || !mapEl || typeof L === "undefined") return; // <noscript> list stays visible

  var places;
  try { places = JSON.parse(dataEl.textContent); } catch (e) { return; }
  var noscript = wrap.parentNode.querySelector("noscript");
  wrap.hidden = false;
  if (noscript) noscript.setAttribute("aria-hidden", "true");

  var filterEl = document.getElementById("pm-filter");
  var listEl = document.getElementById("pm-list");
  var statusEl = document.getElementById("pm-status");
  var hintEl = document.getElementById("pm-hint");
  var touch = !!(window.matchMedia && window.matchMedia("(pointer: coarse)").matches);
  var reduce = window.matchMedia && window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  var map = L.map(mapEl, {
    scrollWheelZoom: false,       // enabled only after the map is clicked / focused
    dragging: !touch,             // one-finger drag would hijack page scroll on phones
    tap: false,
    minZoom: 0, maxZoom: 14,
    zoomSnap: 0.25,
    worldCopyJump: false,
    maxBounds: [[-75, -200], [85, 200]],
    maxBoundsViscosity: 0.8,
    attributionControl: true
  });
  // TILES: CARTO's raster basemaps now watermark every keyless tile ("API KEY REQUIRED", since Sept 2026),
  // so the default is Esri's keyless World Dark Gray canvas (+ labels layer). To switch to CARTO dark_all,
  // get a free key at https://carto.com/basemaps/apikey/ and set CARTO_KEY below.
  var CARTO_KEY = "";
  if (CARTO_KEY) {
    L.tileLayer("https://{s}.basemaps.cartocdn.com/rastertiles/dark_all/{z}/{x}/{y}{r}.png?key=" + CARTO_KEY, {
      subdomains: "abcd", maxZoom: 14,
      attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors &copy; <a href="https://carto.com/attributions">CARTO</a>'
    }).addTo(map);
  } else {
    var esri = "https://server.arcgisonline.com/ArcGIS/rest/services/Canvas/";
    L.tileLayer(esri + "World_Dark_Gray_Base/MapServer/tile/{z}/{y}/{x}", {
      maxZoom: 14, maxNativeZoom: 16,
      attribution: 'Tiles &copy; Esri &mdash; Esri, DeLorme, NAVTEQ &middot; Data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    }).addTo(map);
    L.tileLayer(esri + "World_Dark_Gray_Reference/MapServer/tile/{z}/{y}/{x}", { maxZoom: 14, maxNativeZoom: 16, pane: "shadowPane" }).addTo(map);
  }

  function yearText(p) {
    return (p.years || []).map(function (y) { return y.y + (y.tag ? " (" + y.tag + ")" : ""); }).join(" \u00b7 ");
  }
  function firstYear(p) { return p.years && p.years.length ? Math.min.apply(null, p.years.map(function (y) { return y.y; })) : 9999; }
  function titleFor(p) { var t = yearText(p); return t ? p.name + ", " + t : p.name; }
  places.sort(function (a, b) { return firstYear(a) - firstYear(b) || a.name.localeCompare(b.name); });

  function popupFor(p) {
    var d = document.createElement("div");
    d.className = "pm-popup";
    var h = document.createElement("strong"); h.textContent = p.name; d.appendChild(h);
    var sub = [p.sub, p.note, p.approx ? "Pin at " + p.approx + " (approximate)" : ""].filter(Boolean);
    sub.forEach(function (t) { var s = document.createElement("span"); s.className = "pm-sub"; s.textContent = t; d.appendChild(s); });
    var yt = yearText(p);
    if (yt) { var y = document.createElement("span"); y.className = "pm-years"; y.textContent = yt; d.appendChild(y); }
    if (p.photo && p.photo.src) {
      var f = document.createElement("figure"); f.className = "pm-photo";
      var pic = document.createElement("picture");
      var so = document.createElement("source"); so.type = "image/webp"; so.srcset = p.photo.src + ".webp"; pic.appendChild(so);
      var im = document.createElement("img");
      im.src = p.photo.src + ".jpg"; im.alt = p.photo.alt || ""; im.width = p.photo.w || 800; im.height = p.photo.h || 600; im.decoding = "async";
      // Popup size is measured when it opens; re-fit it (and keep it on screen) once the photo has loaded.
      im.addEventListener("load", function () { if (p.marker && p.marker.isPopupOpen()) { p.marker.getPopup().update(); fitPopup(p); } });
      pic.appendChild(im); f.appendChild(pic);
      if (p.photo.caption) { var fc = document.createElement("figcaption"); fc.textContent = p.photo.caption; f.appendChild(fc); }
      d.appendChild(f);
    }
    return d;
  }

  function fitPopup(p) {
    if (!p.marker || !p.marker.isPopupOpen()) return;
    var el = p.marker.getPopup().getElement();
    if (!el) return;
    var a = el.getBoundingClientRect(), m = mapEl.getBoundingClientRect(), pad = 16, dx = 0, dy = 0;
    if (a.top < m.top + pad) dy = a.top - (m.top + pad); else if (a.bottom > m.bottom - pad) dy = a.bottom - (m.bottom - pad);
    if (a.left < m.left + pad) dx = a.left - (m.left + pad); else if (a.right > m.right - pad) dx = a.right - (m.right - pad);
    if (dx || dy) map.panBy([dx, dy], { animate: !reduce });
  }

  var layer = L.layerGroup().addTo(map);
  var activeItem = null;
  places.forEach(function (p) {
    // 40px hit area around the 22px dot (easier to tap); pins with a photo sit above their neighbours.
    var icon = L.divIcon({ className: "pm-pin" + (p.photo ? " pm-pin-photo" : ""), html: "<span></span>", iconSize: [40, 40], iconAnchor: [20, 20], popupAnchor: [0, -14] });
    p.marker = L.marker([p.lat, p.lng], { icon: icon, title: titleFor(p), alt: p.name, riseOnHover: true, keyboard: true, zIndexOffset: p.photo ? 1000 : 0 });
    p.marker.on("add", function () {
      var el = p.marker.getElement();
      if (!el || el.__pmKey) return;
      el.__pmKey = true;
      el.setAttribute("role", "button");
      el.addEventListener("keydown", function (e) { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); p.marker.openPopup(); } });
    });
    p.marker.bindPopup(popupFor(p), { closeButton: true, autoPan: false, maxWidth: p.photo ? 300 : 260, minWidth: p.photo ? 240 : 50 });
    p.marker.on("popupopen", function () {
      setActive(p);
      // At the zoomed-out overview the map sits at its max bounds, so a tall photo popup cannot pan into view and gets
      // clipped (worst on phones). Zoom to the pin first, then pan the popup fully inside the map.
      if (p.photo && map.getZoom() < 5) {
        map.once("zoomend", function () { setTimeout(function () { fitPopup(p); }, 80); });
        map.setView([p.lat, p.lng], 6, { animate: !reduce });
      } else {
        setTimeout(function () { fitPopup(p); }, 60);
      }
    });
    p.marker.on("popupclose", function () { setActive(null); });

    var li = document.createElement("li");
    var b = document.createElement("button");
    b.type = "button"; b.className = "pm-item";
    var n = document.createElement("span"); n.className = "pm-item-name"; n.textContent = p.name + (p.sub ? " \u2013 " + p.sub : "");
    b.appendChild(n);
    if (yearText(p)) { var yy = document.createElement("span"); yy.className = "pm-item-years"; yy.textContent = yearText(p); b.appendChild(yy); }
    b.addEventListener("click", function () { flyTo(p); });
    li.appendChild(b);
    p.item = li; p.btn = b;
    listEl.appendChild(li);
  });

  function setActive(p) {
    if (activeItem) { activeItem.btn.classList.remove("is-active"); activeItem.btn.removeAttribute("aria-current"); activeItem.marker.getElement() && activeItem.marker.getElement().classList.remove("is-active"); }
    activeItem = p;
    if (p) { p.btn.classList.add("is-active"); p.btn.setAttribute("aria-current", "true"); p.marker.getElement() && p.marker.getElement().classList.add("is-active"); }
  }

  function flyTo(p) {
    var z = Math.max(map.getZoom(), 6);
    var target = [p.lat, p.lng];
    // Open the popup after the camera settles so its auto-pan keeps the (taller) photo popup inside the map.
    map.closePopup();
    if (reduce) { map.setView(target, z, { animate: false }); p.marker.openPopup(); }
    else { map.once("moveend", function () { p.marker.openPopup(); }); map.flyTo(target, z, { duration: 1.1 }); }
    mapEl.scrollIntoView({ block: "nearest", behavior: reduce ? "auto" : "smooth" });
  }

  // Year filter
  var yearSet = {};
  places.forEach(function (p) { (p.years || []).forEach(function (y) { yearSet[y.y] = true; }); });
  var years = Object.keys(yearSet).map(Number).sort(function (a, b) { return a - b; });
  var current = "all";
  var buttons = [];
  function mkBtn(label, val) {
    var b = document.createElement("button");
    b.type = "button"; b.className = "pm-year"; b.textContent = label; b.dataset.val = val;
    b.setAttribute("aria-pressed", val === "all" ? "true" : "false");
    b.addEventListener("click", function () { applyFilter(val); });
    filterEl.appendChild(b); buttons.push(b);
  }
  mkBtn("All", "all");
  years.forEach(function (y) { mkBtn(String(y), String(y)); });

  function fit(list) {
    if (!list.length) return;
    var b = L.latLngBounds(list.map(function (p) { return [p.lat, p.lng]; }));
    var opts = { padding: [36, 36], maxZoom: 7, animate: !reduce };
    if (list.length === 1) map.setView(b.getCenter(), 6, { animate: !reduce }); else map.fitBounds(b, opts);
  }

  function applyFilter(val) {
    current = val;
    buttons.forEach(function (b) { b.setAttribute("aria-pressed", b.dataset.val === val ? "true" : "false"); });
    map.closePopup();
    var shown = places.filter(function (p) { return val === "all" || (p.years || []).some(function (y) { return String(y.y) === val; }); });
    places.forEach(function (p) {
      var on = shown.indexOf(p) !== -1;
      p.item.hidden = !on;
      if (on) layer.addLayer(p.marker); else layer.removeLayer(p.marker);
    });
    statusEl.textContent = val === "all"
      ? places.length + " places, 2011\u20132026."
      : shown.length + (shown.length === 1 ? " place" : " places") + " in " + val + ": " + shown.map(function (p) { return p.name; }).join(", ") + ".";
    fit(shown);
  }

  // Scroll-zoom only after the map is clicked / focused
  function enableWheel() { map.scrollWheelZoom.enable(); hintEl.textContent = "Scroll to zoom. Click outside the map to turn it off."; }
  function disableWheel() { map.scrollWheelZoom.disable(); hintEl.textContent = touch ? "Pinch to zoom. Use the list to explore." : "Click the map to enable scroll-zoom."; }
  map.on("click focus", enableWheel);
  mapEl.addEventListener("mouseleave", disableWheel);
  map.on("blur", disableWheel);
  disableWheel();

  applyFilter("all");
  // Reveal animation / layout shifts: keep tiles sized correctly.
  window.addEventListener("load", function () { map.invalidateSize(); fit(places.filter(function (p) { return !p.item.hidden; })); });
  window.addEventListener("resize", function () { map.invalidateSize(); });
})();
